// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.crophealer.rest.v1;

import com.crophealer.rest.v1.UserAdvisorResource;
import com.crophealer.rest.v1.UserAdvisorResourceList;
import java.util.List;

privileged aspect UserAdvisorResourceList_Roo_JavaBean {
    
    public List<UserAdvisorResource> UserAdvisorResourceList.getUserAdvisors() {
        return this.userAdvisors;
    }
    
    public void UserAdvisorResourceList.setUserAdvisors(List<UserAdvisorResource> userAdvisors) {
        this.userAdvisors = userAdvisors;
    }
    
}
