// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.crophealer.rest.v1;

import com.crophealer.rest.v1.UserAdvisorResource;

privileged aspect UserAdvisorResource_Roo_JavaBean {
    
    public Long UserAdvisorResource.getId() {
        return this.id;
    }
    
    public void UserAdvisorResource.setId(Long id) {
        this.id = id;
    }
    
    public Long UserAdvisorResource.getClientId() {
        return this.clientId;
    }
    
    public void UserAdvisorResource.setClientId(Long clientId) {
        this.clientId = clientId;
    }
    
    public Long UserAdvisorResource.getAdvisorId() {
        return this.advisorId;
    }
    
    public void UserAdvisorResource.setAdvisorId(Long advisorId) {
        this.advisorId = advisorId;
    }
    
    public String UserAdvisorResource.getStatus() {
        return this.status;
    }
    
    public void UserAdvisorResource.setStatus(String status) {
        this.status = status;
    }
    
}
