// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.crophealer.domain;

import com.crophealer.domain.DiagnosedProblem;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DiagnosedProblem_Roo_Configurable {
    
    declare @type: DiagnosedProblem: @Configurable;
    
}
