// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.crophealer.domain;

import com.crophealer.domain.UserAdvisor;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect UserAdvisor_Roo_Jpa_Entity {
    
    declare @type: UserAdvisor: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long UserAdvisor.id;
    
    @Version
    @Column(name = "version")
    private Integer UserAdvisor.version;
    
    public Long UserAdvisor.getId() {
        return this.id;
    }
    
    public void UserAdvisor.setId(Long id) {
        this.id = id;
    }
    
    public Integer UserAdvisor.getVersion() {
        return this.version;
    }
    
    public void UserAdvisor.setVersion(Integer version) {
        this.version = version;
    }
    
}
