// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.crophealer.domain;

import com.crophealer.domain.UserAdvisor;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserAdvisor_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager UserAdvisor.entityManager;
    
    public static final EntityManager UserAdvisor.entityManager() {
        EntityManager em = new UserAdvisor().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long UserAdvisor.countUserAdvisors() {
        return entityManager().createQuery("SELECT COUNT(o) FROM UserAdvisor o", Long.class).getSingleResult();
    }
    
    public static List<UserAdvisor> UserAdvisor.findAllUserAdvisors() {
        return entityManager().createQuery("SELECT o FROM UserAdvisor o", UserAdvisor.class).getResultList();
    }
    
    public static UserAdvisor UserAdvisor.findUserAdvisor(Long id) {
        if (id == null) return null;
        return entityManager().find(UserAdvisor.class, id);
    }
    
    public static List<UserAdvisor> UserAdvisor.findUserAdvisorEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM UserAdvisor o", UserAdvisor.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void UserAdvisor.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void UserAdvisor.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            UserAdvisor attached = UserAdvisor.findUserAdvisor(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void UserAdvisor.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void UserAdvisor.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public UserAdvisor UserAdvisor.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        UserAdvisor merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
