// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.crophealer.security;

import com.crophealer.security.Users;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Users_Roo_Configurable {
    
    declare @type: Users: @Configurable;
    
}
